# Generated by Django 5.1.15 on 2026-10-08 18:19

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro en el puesto'), ('domicilio', 'Domicilio')], default='retiro', max_length=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('direccion_entrega', models.CharField(blank=True, help_text='Obligatorio cuando tipo_entrega=domicilio.', max_length=200)),
                ('referencia_entrega', models.CharField(blank=True, help_text='Referencia para encontrar el sitio: color de la casa, portón, etc.', max_length=150)),
                ('notas', models.TextField(blank=True, help_text='Notas del comprador para el vendedor.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tarifa_domicilio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarifa de domicilio; se cobra cuando la fase de pagos esté activa.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='comprador')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='catalog.puesto', verbose_name='puesto')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=120)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('libra', 'Libra'), ('unidad', 'Unidad'), ('docena', 'Docena'), ('litro', 'Litro'), ('porcion', 'Porción')], max_length=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_producto', models.ForeignKey(help_text='PROTECT: el producto referenciado por un pedido no se borra (historial).', on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='catalog.producto', verbose_name='producto')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'ítem de pedido',
                'verbose_name_plural': 'ítems de pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmado', 'en_preparacion', 'en_camino', 'entregado', 'cancelado'])), name='pedido_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_entrega__in', ['retiro', 'domicilio'])), name='pedido_tipo_entrega_valido'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tarifa_domicilio__gte', 0), ('total__gte', 0)), name='pedido_totales_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('tarifa_domicilio')))), name='pedido_total_es_subtotal_mas_tarifa'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_entrega', 'retiro'), models.Q(('direccion_entrega', ''), _negated=True), _connector='OR'), name='pedido_domicilio_requiere_direccion'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('id_pedido', 'id_producto'), name='itempedido_producto_unico_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='itempedido_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='itempedido_precio_no_negativo'),
        ),
    ]
