# Generated by Django 5.1.15 on 2026-10-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_direccion',
            field=models.ForeignKey(blank=True, help_text='Dirección reutilizada (snapshot); se conserva aunque se borre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='addresses.direccion', verbose_name='dirección guardada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='latitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitud_entrega__isnull', True), ('longitud_entrega__isnull', True)), models.Q(('latitud_entrega__isnull', False), ('longitud_entrega__isnull', False)), _connector='OR'), name='pedido_coordenadas_completas'),
        ),
    ]
