# Generated by Django 5.1.15 on 2026-10-09 18:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_direccion_entrega'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_totales_no_negativos',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_total_es_subtotal_mas_tarifa',
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_cupon',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
