# Generated by Django 5.1.15 on 2026-10-09 18:59

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0003_remove_pedido_pedido_totales_no_negativos_and_more'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_cupon',
            field=models.ForeignKey(blank=True, help_text='Snapshot del cupón usado; sobrevive aunque se borre el cupón.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='promotions.cupon', verbose_name='cupón aplicado'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tarifa_domicilio__gte', 0), ('descuento_cupon__gte', 0), ('total__gte', 0)), name='pedido_totales_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('tarifa_domicilio')), '-', models.F('descuento_cupon')))), name='pedido_total_es_subtotal_mas_tarifa_menos_descuento'),
        ),
    ]
