# Generated by Django 5.1.15 on 2026-10-08 01:13

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='correo')),
                ('celular', models.CharField(db_index=True, max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('administrador', 'Administrador')], default='comprador', max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-fecha_registro'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rol__in', ['comprador', 'vendedor', 'administrador'])), name='usuario_rol_valido'), models.CheckConstraint(condition=models.Q(('estado__in', ['activo', 'suspendido'])), name='usuario_estado_valido')],
            },
            managers=[
                ('objects', apps.accounts.models.UsuarioManager()),
            ],
        ),
    ]
