# Generated by Django 5.1.15 on 2026-10-08 03:00

import apps.common.storage
import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cedula', models.BinaryField(blank=True, help_text='Cifrado con Fernet; nunca se guarda en claro.', max_length=512, null=True, verbose_name='número de cédula')),
                ('cedula_huella', models.CharField(blank=True, help_text='HMAC-SHA256 para unicidad sin descifrar (regla 6).', max_length=64, null=True, unique=True, verbose_name='huella de cédula')),
                ('foto_cedula', models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to='cedulas/', validators=[apps.common.validators.validate_image_file], verbose_name='foto de cédula')),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15, verbose_name='estado de verificación')),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('id_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisor')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'verificación de vendedor',
                'verbose_name_plural': 'verificaciones de vendedor',
                'ordering': ['fecha_solicitud'],
                'constraints': [models.CheckConstraint(condition=models.Q(('estado_verificacion__in', ['pendiente', 'aprobado', 'rechazado'])), name='vendedor_estado_verificacion_valido')],
            },
        ),
    ]
