[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
pythonpath = .
python_files = test_*.py
testpaths = tests apps
norecursedirs = .git .venv venv staticfiles media dist build __pycache__
addopts = -ra --strict-markers
markers =
    slow: pruebas lentas
