# Generated by Django 5.1.15 on 2026-10-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Etiqueta corta: Casa, Trabajo, etc.', max_length=50)),
                ('direccion', models.CharField(help_text='Dirección de entrega.', max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='Cómo llegar: color de la casa, portón, punto de referencia.', max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['-es_predeterminada', '-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_predeterminada', True)), fields=('id_usuario',), name='direccion_predeterminada_unica_por_usuario'), models.CheckConstraint(condition=models.Q(models.Q(('latitud__isnull', True), ('longitud__isnull', True)), models.Q(('latitud__isnull', False), ('longitud__isnull', False)), _connector='OR'), name='direccion_coordenadas_completas'), models.CheckConstraint(condition=models.Q(('es_predeterminada', False), ('activa', True), _connector='OR'), name='direccion_predeterminada_activa')],
            },
        ),
    ]
