# Generated by Django 5.1.15 on 2026-10-09 18:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0003_remove_pedido_pedido_totales_no_negativos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (1-100) o monto fijo en pesos.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_minimo_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tope_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento máximo (aplica a porcentajes).', max_digits=10, null=True)),
                ('usos_totales', models.PositiveIntegerField(blank=True, help_text='Total de usos permitidos (vacío = ilimitado).', null=True)),
                ('usos_por_usuario', models.PositiveIntegerField(blank=True, help_text='Usos permitidos por usuario (vacío = ilimitado).', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_puesto', models.ForeignKey(blank=True, help_text='Vacío = cupón global del marketplace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones', to='catalog.puesto', verbose_name='puesto')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('id_cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='promotions.cupon')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_cupon', to='orders.pedido', verbose_name='pedido')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cupones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uso de cupón',
                'verbose_name_plural': 'usos de cupones',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_descuento__in', ['porcentaje', 'monto'])), name='cupon_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='cupon_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_descuento', 'monto'), ('valor__lte', 100), _connector='OR'), name='cupon_porcentaje_no_excede_100'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_inicio__lte', models.F('fecha_fin')), _connector='OR'), name='cupon_fechas_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.CheckConstraint(condition=models.Q(('usos_totales__isnull', True), ('usos_totales__gt', 0), _connector='OR'), name='cupon_usos_totales_positivos'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.CheckConstraint(condition=models.Q(('usos_por_usuario__isnull', True), ('usos_por_usuario__gt', 0), _connector='OR'), name='cupon_usos_por_usuario_positivos'),
        ),
        migrations.AddConstraint(
            model_name='usocupon',
            constraint=models.UniqueConstraint(fields=('id_pedido',), name='uso_cupon_unico_por_pedido'),
        ),
    ]
