# Generated by Django 5.1.15 on 2026-10-09 04:03

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta debito/credito'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('simulado', 'Simulado (sandbox)')], default='simulado', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado'), ('anulado', 'Anulado')], default='pendiente', max_length=15)),
                ('subtotal_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tarifa_domicilio_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('referencia_gateway', models.CharField(blank=True, max_length=120)),
                ('datos_sandbox', models.JSONField(blank=True, default=dict)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('id_pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='orders.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'procesando', 'aprobado', 'rechazado', 'reembolsado', 'anulado'])), name='pago_estado_valido'), models.CheckConstraint(condition=models.Q(('metodo_pago__in', ['efectivo', 'transferencia', 'tarjeta', 'nequi', 'daviplata', 'simulado'])), name='pago_metodo_valido'), models.CheckConstraint(condition=models.Q(('subtotal_pedido__gte', 0), ('tarifa_domicilio_aplicada__gte', 0), ('comision_plataforma__gte', 0), ('total_cobrado__gte', 0)), name='pago_montos_no_negativos'), models.CheckConstraint(condition=models.Q(('total_cobrado', django.db.models.expressions.CombinedExpression(models.F('subtotal_pedido'), '+', models.F('tarifa_domicilio_aplicada')))), name='pago_total_coincide_con_subtotal_mas_domicilio')],
            },
        ),
    ]
