# Generated by Django 5.1.15 on 2026-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_reembolso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
