# Generated by Django 5.1.15 on 2026-10-09 18:59

import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_pedido_pedido_totales_no_negativos_and_more'),
        ('payments', '0002_pago_fecha_reembolso'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_montos_no_negativos',
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_total_coincide_con_subtotal_mas_domicilio',
        ),
        migrations.AddField(
            model_name='pago',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento del cupón aplicado al pedido (lo asume el vendedor).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_pedido__gte', 0), ('tarifa_domicilio_aplicada__gte', 0), ('comision_plataforma__gte', 0), ('descuento_aplicado__gte', 0), ('total_cobrado__gte', 0)), name='pago_montos_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('total_cobrado', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_pedido'), '+', models.F('tarifa_domicilio_aplicada')), '-', models.F('descuento_aplicado')))), name='pago_total_coincide_con_subtotal_mas_domicilio'),
        ),
    ]
