# Generated by Django 5.1.15 on 2026-10-09 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('transicion', 'Transición de estado'), ('aprobar', 'Aprobar'), ('rechazar', 'Rechazar'), ('reembolsar', 'Reembolsar'), ('anular', 'Anular'), ('usar_cupon', 'Usar cupón'), ('responder', 'Responder')], max_length=20)),
                ('entidad', models.CharField(max_length=50)),
                ('id_entidad', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['entidad', 'id_entidad'], name='auditoria_entidad_idx'), models.Index(fields=['accion'], name='auditoria_accion_idx'), models.Index(fields=['fecha_creacion'], name='auditoria_fecha_idx')],
            },
        ),
    ]
