# Generated by Django 5.1.15 on 2026-10-08 02:11

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('id_categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('libra', 'Libra'), ('unidad', 'Unidad'), ('docena', 'Docena'), ('litro', 'Litro'), ('porcion', 'Porción')], default='unidad', max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=15)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(help_text='JPEG/PNG/WebP, máximo 2 MB.', upload_to='productos/%Y/%m/', validators=[apps.common.validators.validate_image_file])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('ofrece_domicilio', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalog.puesto'),
        ),
        migrations.CreateModel(
            name='PuestoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='catalog.categoria')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_asignadas', to='catalog.puesto')),
            ],
            options={
                'verbose_name': 'puesto-categoría',
                'verbose_name_plural': 'puestos-categorías',
                'ordering': ['id_puesto', 'id_categoria'],
            },
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['activo', 'inactivo', 'suspendido'])), name='puesto_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.CheckConstraint(condition=models.Q(('ofrece_domicilio', False), models.Q(('latitud__isnull', False), ('longitud__isnull', False)), _connector='OR'), name='puesto_domicilio_requiere_coordenadas'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', Decimal('0'))), name='producto_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['activo', 'inactivo', 'bloqueado'])), name='producto_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('unidad_medida__in', ['kg', 'libra', 'unidad', 'docena', 'litro', 'porcion'])), name='producto_unidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='puestocategoria',
            constraint=models.UniqueConstraint(fields=('id_puesto', 'id_categoria'), name='puesto_categoria_unica'),
        ),
    ]
