# Generated by Django 5.1.15 on 2026-10-09 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0002_pedido_direccion_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_pedido', models.ForeignKey(blank=True, help_text='Pedido entregado que origina la reseña (auditoría).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='orders.pedido', verbose_name='pedido')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='catalog.puesto', verbose_name='puesto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL, verbose_name='comprador')),
            ],
            options={
                'verbose_name': 'reseña',
                'verbose_name_plural': 'reseñas',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='resena_calificacion_valida'), models.UniqueConstraint(fields=('id_usuario', 'id_puesto'), name='resena_unica_por_usuario_y_puesto')],
            },
        ),
    ]
