# Generated by Django 5.1.15 on 2026-10-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('pedido_confirmado', 'Pedido confirmado'), ('pedido_en_preparacion', 'Pedido en preparación'), ('pedido_en_camino', 'Pedido en camino'), ('pedido_entregado', 'Pedido entregado'), ('pedido_cancelado', 'Pedido cancelado'), ('pago_aprobado', 'Pago aprobado'), ('pago_rechazado', 'Pago rechazado'), ('verificacion', 'Verificación'), ('general', 'General')], max_length=30)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='orders.pedido', verbose_name='pedido')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['pedido_creado', 'pedido_confirmado', 'pedido_en_preparacion', 'pedido_en_camino', 'pedido_entregado', 'pedido_cancelado', 'pago_aprobado', 'pago_rechazado', 'verificacion', 'general'])), name='notificacion_tipo_valido')],
            },
        ),
    ]
